name: run-tests

on:
  push:
    branches:
      - v1
      - v2
      - v2-compatible
  pull_request:
    branches:
      - v1
      - v2
      - v2-compatible
  schedule:
    - cron: "0 9 1 * *"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go:
          - 1.17
          - 1.18
        clickhouse:
          - 19.11
          - 20.1
          - 21.11
          - 22.1
          - latest

    services:
      clickhouse:
        image: yandex/clickhouse-server:${{ matrix.clickhouse }}
        ports:
          - 9000:9000
        options: --ulimit nofile=262144:262144

    steps:
      - uses: actions/checkout@v2

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2.1.5
        with:
          stable: false
          go-version: ${{ matrix.go }}

      - name: Run tests
        run: |
          go test -v .
          go test -v ./tests
          go test -v ./lib/...
